### ISSUE TITLE
Эй! v2.0

### ISSUE THREAD

**Issue by png2378** [inpr1se/ZloyBot#4]
PIDORA OTWET!!1

**Comment by Defman21** [comment]
vot tut ti ne prav

**Comment by inpr1se** [comment]
c9a32194f583748b5114333abdab6d74811c17fc pidori

**Comment by png2378** [comment]
После такого финта ушами, шлю проект "ZloyBot" на хуй.

**Comment by Defman21** [comment]
so sad
